name: LifeNexus
options:
  bundleIdPrefix: com.lifenexus
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: YES

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: 2.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.0.0
  Lottie:
    url: https://github.com/airbnb/lottie-spm
    from: 4.0.0

targets:
  LifeNexus:
    type: application
    platform: iOS
    sources:
      - path: LifeNexus
        excludes:
          - "**/.DS_Store"
    resources:
      - path: LifeNexus/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifenexus.app
        PRODUCT_NAME: LifeNexus
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_CFBundleDisplayName: LifeNexus
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: Supabase
      - package: Firebase
        product: FirebaseAI
      - package: Lottie
    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

  LifeNexusTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LifeNexusTests
    dependencies:
      - target: LifeNexus
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lifenexus.app.tests

schemes:
  LifeNexus:
    build:
      targets:
        LifeNexus: all
        LifeNexusTests: [test]
    run:
      config: Debug
      simulateLocation:
        allow: true
    test:
      config: Debug
      targets:
        - LifeNexusTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
